### ISSUE TITLE
How can I use the docred dataset with strict evaluation

### ISSUE THREAD

**Issue by xwm-123** [Babelscape/rebel#12]
When I am trying to train the model on docred dataset, inputing python train.py model=rebel_model data=docred_data train=docred_train, but the model can't run correctly and return

Traceback (most recent call last):
  File "/home/weimin/rebel/src/train.py", line 150, in main
    train(conf)
  File "/home/weimin/rebel/src/train.py", line 146, in train
    trainer.fit(pl_module, datamodule=pl_data_module)
  File "/home/weimin/anaconda3/envs/rebel/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 510, in fit
    results = self.accelerator_backend.train()
  File "/home/weimin/anaconda3/envs/rebel/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 57, in train
    return self.train_or_test()
  File "/home/weimin/anaconda3/envs/rebel/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in train_or_test
    results = self.trainer.train()
  File "/home/weimin/anaconda3/envs/rebel/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 532, in train
    self.run_sanity_check(self.get_model())
  File "/home/weimin/anaconda3/envs/rebel/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 730, in run_sanity_check
    _, eval_results = self.run_evaluation(max_batches=self.num_sanity_val_batches)
  File "/home/weimin/anaconda3/envs/rebel/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 662, in run_evaluation
    deprecated_eval_results = self.evaluation_loop.evaluation_epoch_end()
  File "/home/weimin/anaconda3/envs/rebel/lib/python3.9/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 210, in evaluation_epoch_end
    deprecated_results = self.__run_eval_epoch_end(self.num_dataloaders, using_eval_result)
  File "/home/weimin/anaconda3/envs/rebel/lib/python3.9/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 248, in __run_eval_epoch_end
    eval_results = model.validation_epoch_end(eval_results)
  File "/home/weimin/rebel/src/pl_modules.py", line 392, in validation_epoch_end
    scores, precision, recall, f1 = re_score([item for pred in output for item in pred['predictions']], [item for pred in output for item in pred['labels']], list(relations_docred.values()), "strict")
  File "/home/weimin/rebel/src/score.py", line 174, in re_score
    pred_rels = {(rel["head"], rel["head_type"], rel["tail"], rel["tail_type"]) for rel in pred_sent if
  File "/home/weimin/rebel/src/score.py", line 174, in <setcomp>
    pred_rels = {(rel["head"], rel["head_type"], rel["tail"], rel["tail_type"]) for rel in pred_sent if
KeyError: 'head_type'

And I check the code in the function re_score, I found the output of this model only contains "head", "tail" and "type". What's wrong with it?

**Comment by xwm-123** [comment]
The output is like [{'head': 'Skai TV', 'type': 'headquarters location', 'tail': 'Piraeus'}].
How can I adjust the model to output (start_idx (inclusive), end_idx (exclusive))

**Comment by LittlePea13** [comment]
Thank you very much for bringing this up.

I somehow lost two lines when cleaning the code for release. I have updated the code with the fix:
https://github.com/Babelscape/rebel/blob/71ef4379766e4713946fc2927e3f31329302ef1c/src/pl_modules.py#L195-L196

This will also extract the entity types and won't return an error.

Sorry for the inconvenience.

**Comment by xwm-123** [comment]
Thank you for this! I had just fixed it. And I want to ask what is the function of conf.finetune?
The default value is False. Does it mean that model will be trainned from scratch? Do I need to adjust it to True to finetune on my dataset?

**Comment by LittlePea13** [comment]
Hi, that is some legacy parameter, not really used anymore. The model is always trained from a BART checkpoint, but that is defined by "model_name_or_path", "config_name" and "tokenizer_name". You can finetune from just pretrained BART or from the REBEL pre-trained on the silver data checkpoint.

**Comment by xwm-123** [comment]
Thanks！
