### ISSUE TITLE
when train docred issue!

### ISSUE THREAD

**Issue by KIMDOKYOUNG** [Babelscape/rebel#13]
hi, 
when training docred, when i used one gpu , it have CUDA out of memory.
so i used tow gpus 

I modified the gpus of docred_train.yaml as follows
gpus: [0, 1]

but it doesn't work.

(REBEL) kdk@Z370-Pro4:~/rebel/src$ HYDRA_FULL_ERROR=1 python train.py model=rebel_model data=docred_data train=docred_train
Global seed set to 42
[2022-04-01 14:17:19,346][datasets.builder][WARNING] - Using custom data configuration default-5a4186527af1c5d2
[2022-04-01 14:17:19,346][datasets.builder][WARNING] - Reusing dataset doc_red (/home/kdk/.cache/huggingface/datasets/doc_red/default-5a4186527af1c5d2/0.0.0/2cc6999b276b6aa2b2af5101b416c33155e5f19e6f0b26864a2312d1aa57b175)
/home/kdk/anaconda3/envs/REBEL/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py:50: UserWarning: You requested multiple GPUs but did not specify a backend, e.g. `Trainer(accelerator="dp"|"ddp"|"ddp2")`. Setting `accelerator="ddp_spawn"` for you.
  warnings.warn(*args, **kwargs)
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Using native 16bit precision.
[2022-04-01 14:17:20,609][datasets.arrow_dataset][WARNING] - Loading cached processed dataset at /home/kdk/rebel/data/datasets/docred_joint/train_joint.jsondocred_typed.cache
[2022-04-01 14:17:21,774][datasets.arrow_dataset][WARNING] - Loading cached processed dataset at /home/kdk/rebel/data/datasets/docred_joint/dev_joint.jsondocred_typed.cache
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Global seed set to 42
/home/kdk/anaconda3/envs/REBEL/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py:50: UserWarning: MASTER_ADDR environment variable is not defined. Set as localhost
  warnings.warn(*args, **kwargs)
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/2
Global seed set to 42
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/2
Traceback (most recent call last):
  File "train.py", line 151, in <module>
    main()
  File "/home/kdk/anaconda3/envs/REBEL/lib/python3.7/site-packages/hydra/main.py", line 37, in decorated_main
    strict=strict,
  File "/home/kdk/anaconda3/envs/REBEL/lib/python3.7/site-packages/hydra/_internal/utils.py", line 347, in _run_hydra
    lambda: hydra.run(
  File "/home/kdk/anaconda3/envs/REBEL/lib/python3.7/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/home/kdk/anaconda3/envs/REBEL/lib/python3.7/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/kdk/anaconda3/envs/REBEL/lib/python3.7/site-packages/hydra/_internal/utils.py", line 350, in <lambda>
    overrides=args.overrides,
  File "/home/kdk/anaconda3/envs/REBEL/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 112, in run
    configure_logging=with_log_configuration,
  File "/home/kdk/anaconda3/envs/REBEL/lib/python3.7/site-packages/hydra/core/utils.py", line 127, in run_job
    ret.return_value = task_function(task_cfg)
  File "train.py", line 147, in main
    train(conf)
  File "train.py", line 143, in train
    trainer.fit(pl_module, datamodule=pl_data_module)
  File "/home/kdk/anaconda3/envs/REBEL/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 510, in fit
    results = self.accelerator_backend.train()
  File "/home/kdk/anaconda3/envs/REBEL/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_spawn_accelerator.py", line 83, in train
    mp.spawn(self.ddp_train, nprocs=self.nprocs, args=(self.mp_queue, model,))
  File "/home/kdk/anaconda3/envs/REBEL/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/kdk/anaconda3/envs/REBEL/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/home/kdk/anaconda3/envs/REBEL/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/kdk/anaconda3/envs/REBEL/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/kdk/anaconda3/envs/REBEL/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_spawn_accelerator.py", line 174, in ddp_train
    self.trainer.setup_trainer(model)
  File "/home/kdk/anaconda3/envs/REBEL/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 442, in setup_trainer
    self.logger.log_hyperparams(ref_model.hparams_initial)
  File "/home/kdk/anaconda3/envs/REBEL/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py", line 40, in wrapped_fn
    return fn(*args, **kwargs)
  File "/home/kdk/anaconda3/envs/REBEL/lib/python3.7/site-packages/pytorch_lightning/loggers/wandb.py", line 170, in log_hyperparams
    self.experiment.config.update(params, allow_val_change=True)
  File "/home/kdk/anaconda3/envs/REBEL/lib/python3.7/site-packages/pytorch_lightning/loggers/base.py", line 39, in experiment
    return get_experiment() or DummyExperiment()
  File "/home/kdk/anaconda3/envs/REBEL/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py", line 40, in wrapped_fn
    return fn(*args, **kwargs)
  File "/home/kdk/anaconda3/envs/REBEL/lib/python3.7/site-packages/pytorch_lightning/loggers/base.py", line 38, in get_experiment
    return fn(self)
  File "/home/kdk/anaconda3/envs/REBEL/lib/python3.7/site-packages/pytorch_lightning/loggers/wandb.py", line 152, in experiment
    id=self._id, resume='allow', **self._kwargs) if wandb.run is None else wandb.run
  File "/home/kdk/anaconda3/envs/REBEL/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 741, in init
    wi.setup(kwargs)
  File "/home/kdk/anaconda3/envs/REBEL/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 155, in setup
    wandb_login._login(anonymous=anonymous, force=force, _disable_warning=True)
  File "/home/kdk/anaconda3/envs/REBEL/lib/python3.7/site-packages/wandb/sdk/wandb_login.py", line 210, in _login
    wlogin.prompt_api_key()
  File "/home/kdk/anaconda3/envs/REBEL/lib/python3.7/site-packages/wandb/sdk/wandb_login.py", line 147, in prompt_api_key
    raise UsageError("api_key not configured (no-tty).  Run wandb login")
wandb.errors.UsageError: api_key not configured (no-tty).  Run wandb login

Do you know this issue?
I want to solve this problem!!

thank you.

**Comment by LittlePea13** [comment]
Hi there, unfortunately we didn't test Rebel for ddp or dp training with multiple GPUs so we cannot ensure it works.

However since it is based on Pytorch Lightning it shouldn't be too hard to make it work. If you manage to do so, feel free to do a PR with the changes.
