### ISSUE TITLE
NYT dataset, on_train_batch_end, there is no labels in batch

### ISSUE THREAD

**Issue by kk19990709** [Babelscape/rebel#29]
on_train_batch_end(), there is no "labels" key, and run code `labels = batch.pop("labels")`, thus raised KeyError.

**Comment by kk19990709** [comment]
```
/home/deeplearning/anaconda3/envs/rebel/lib/python3.7/site-packages/torch/optim/lr_scheduler.py:136: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
Epoch 0:  14%|████████▎                                                    | 999/7338 [07:24<46:58,  2.25it/s, loss=0.977, v_num=i4xd]Saving latest checkpoint...
Traceback (most recent call last):
  File "/home/deeplearning/anaconda3/envs/rebel/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 561, in train
    self.train_loop.run_training_epoch()
  File "/home/deeplearning/anaconda3/envs/rebel/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 556, in run_training_epoch
    self.on_train_batch_end(epoch_output, batch_end_outputs, batch, batch_idx, dataloader_idx)
  File "/home/deeplearning/anaconda3/envs/rebel/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 226, in on_train_batch_end
    self.trainer.call_hook('on_train_batch_end', batch_end_outputs, batch, batch_idx, dataloader_idx)
  File "/home/deeplearning/anaconda3/envs/rebel/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 925, in call_hook
    trainer_hook(*args, **kwargs)
  File "/home/deeplearning/anaconda3/envs/rebel/lib/python3.7/site-packages/pytorch_lightning/trainer/callback_hook.py", line 147, in on_train_batch_end
    callback.on_train_batch_end(self, self.get_model(), outputs, batch, batch_idx, dataloader_idx)
  File "/data/kk/rebel/src/generate_samples.py", line 39, in on_train_batch_end
    if (trainer.batch_idx + 1) % self.logging_batch_interval != 0:  # type: ignore[attr-defined]
  File "/home/deeplearning/anaconda3/envs/rebel/lib/python3.7/_collections_abc.py", line 795, in pop
    value = self[key]
  File "/home/deeplearning/anaconda3/envs/rebel/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 236, in __getitem__
    return self.data[item]
KeyError: 'labels'
```

**Comment by kk19990709** [comment]
In pytorch_lightning/trainer/training_loop.py/【class】TrainLoop/【def】run_training_epoch, I find a TODO. This may related to this issue.
```
            # hook
            # TODO: add outputs to batches
            self.on_train_batch_end(epoch_output, batch_end_outputs, batch, batch_idx, dataloader_idx)
```

**Comment by LittlePea13** [comment]
It seems to be an issue with the callback (from `generate_samples.py`). I will check and get back to you but if you want to avoid the error for now, just deactivate that callback as it has no effect on training, it is just to check generation on train samples during training.

**Comment by kk19990709** [comment]
Thanks a lot, I have already deactivated it and trained.
By the way, I found that generate models get excellent performance with a large amount of training data, **BUT** get a low performance in few-shot setting (small dataset or long-tail classes). Is it normal?

**Comment by kk19990709** [comment]
Thanks for you reply!

**Comment by bablf** [comment]
Ran into the same problem. pytorch-lightning verision 1.1.7 fixes the error. 

> By the way, I found that generate models get excellent performance with a large amount of training data, BUT get a low performance in few-shot setting (small dataset or long-tail classes). Is it normal?

@kk19990709 to clarify: you are just talking about low resource settings right? Not actual few-shot classification/learning right?

**Comment by kk19990709** [comment]
@bablf Yes, I mean low resource settings. About 1k-3k examples in train dataset.
