### ISSUE TITLE
Error when training on DocRED: expected str, bytes or os.PathLike object, not DataFilesList

### ISSUE THREAD

**Issue by Iqra840** [Babelscape/rebel#32]
When evaluating on the DocRED dataset, I'm receiving the following error with traceback. I tried replacing the model variable with the path string but made no difference. I would be grateful for any hints regarding this. 

`
C:\Users\i.abbasi\rebel\src> python train.py model=rebel_model data=docred_data train=docred_train
Global seed set to 42
[2022-08-07 18:30:34,790][datasets.builder][WARNING] - Using custom data configuration default-e2fda1423ea7b8aa
Downloading and preparing dataset docred_typed/default to C:\Users\i.abbasi\.cache\huggingface\datasets\docred_typed\default-e2fda1423ea7b8aa\0.0.0\2cc6999b276b6aa2b2af5101b416c33155e5f19e6f0b26864a2312d1aa57b175...
Generating train split: 0 examples [00:00, ? examples/s][2022-08-07 18:30:35,303][root][INFO] - generating examples from = [WindowsPath('C:/Users/i.abbasi/rebel/data/docred_joint/train_joint.json')]
Traceback (most recent call last):
  File "train.py", line 106, in main
    train(conf)
  File "train.py", line 54, in train
    pl_data_module = BasePLDataModule(conf, tokenizer, model)
  File "C:\Users\i.abbasi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pytorch_lightning\core\datamodule.py", line 49, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "C:\Users\i.abbasi\rebel\src\pl_data_modules.py", line 68, in __init__
    self.datasets = load_dataset(conf.dataset_name, data_files={'train': conf.train_file, 'dev': conf.validation_file, 'test': conf.test_file})
  File "C:\Users\i.abbasi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\datasets\load.py", line 1679, in load_dataset
    builder_instance.download_and_prepare(
  File "C:\Users\i.abbasi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\datasets\builder.py", line 704, in download_and_prepare
    self._download_and_prepare(
  File "C:\Users\i.abbasi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\datasets\builder.py", line 1221, in _download_and_prepare
    super()._download_and_prepare(dl_manager, verify_infos, check_duplicate_keys=verify_infos)
  File "C:\Users\i.abbasi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\datasets\builder.py", line 793, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "C:\Users\i.abbasi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\datasets\builder.py", line 1204, in _prepare_split
    for key, record in logging.tqdm(
  File "C:\Users\i.abbasi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "C:\Users\i.abbasi\.cache\huggingface\modules\datasets_modules\datasets\docred_typed\2cc6999b276b6aa2b2af5101b416c33155e5f19e6f0b26864a2312d1aa57b175\docred_typed.py", line 101, in _generate_examples
    with open(filepath) as json_file:
  File "C:\Users\i.abbasi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\datasets\streaming.py", line 67, in wrapper
    return function(*args, use_auth_token=use_auth_token, **kwargs)
  File "C:\Users\i.abbasi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\datasets\download\streaming_download_manager.py", line 423, in xopen
    file = _as_posix(PurePath(file))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 651, in __new__
    return cls._from_parts(args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 683, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 667, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not DataFilesList

`

**Comment by LittlePea13** [comment]
If I am not mistaken, that comes from a breaking change with an update of the datasets library, in which the path is transformed to a DataFilesList, probably in order to allow for inputting several files. Since Rebel was coded with an older version, you can either downgrade or go to this line:
https://github.com/Babelscape/rebel/blob/7bc0602908c4771fda54e08c5bfd13cfba9d5820/datasets/docred_typed.py#L101

And do str(filepath[0]). There's probably a more appropriate way to deal with this but I'm on vacation so don't have the time to check properly 😉

Best of luck,
Pere-Lluís

**Comment by kizunasunhy** [comment]
Datasets downgrade to 1.3.0 will solve this.

**Comment by LittlePea13** [comment]
Since that is the version on reqs, I am closing this.
