### ISSUE TITLE
Datasets Related Problems

### ISSUE THREAD

**Issue by DantaAlighieri** [Babelscape/rebel#7]
Excuse me, I run your model with NYT datasets. However, it failed.
I guess whether my dataset is right or wrong.  the error printed seems to show there are some problems with the data type.
Please see the pictures as follow.

picture1: I run the train.py,  the problems occur in load_datasets functions.
picture2: the NYT dataset(train.data). I download from the [Copy_RE github](https://github.com/xiangrongzeng/copy_re).
picture3: I write a test function to run the load_datasets functions. It still cannot work.

so, I don't know whether my dataset is right or wrong. 
the follow code also cannot run. because there is no **spo_list** or **spo_details** in datasets. 
`list_relations = zip(row['spo_list'], row['spo_details'])`

![picture1](https://user-images.githubusercontent.com/56987319/152272246-622f33bb-fe5c-4868-a1e3-a97e829a6d06.png)
![picutre2](https://user-images.githubusercontent.com/56987319/152272248-b4980603-5a62-4193-a4e3-e40042f883cd.png)
![picture3](https://user-images.githubusercontent.com/56987319/152272251-d21c6729-e5f5-41ca-9080-c93de1a45294.png)

Thank you very much!

**Comment by DantaAlighieri** [comment]
I modified my transformer and datasets version,  because of the same issues from this problem.
[AssertionError: Non-consecutive added token '<obj>' found. Should have index 50272 but has index 50265 in saved vocabulary.]

**Comment by LittlePea13** [comment]
Could you please give a bit more information about the current issue?

For NYT you need to add the following special tokens, as done in this line:
https://github.com/Babelscape/rebel/blob/2a89e1a50f4701fdf6563bcb6a8b7f137e2dafbb/src/train.py#L82

**Comment by DantaAlighieri** [comment]
Thank you very much for your reply in your busy time.
I added the special tokens this morning.
I found the problem is in nyt_typed.py.
the file path is not a string. it is [PosixPath('/tmp/xxxx/datasets/data/nyt/train.json')] form.
so, I modify the path to string, however, there maybe some problems in following command.
`list_relations = zip(row['spo_list'],row['spo_details'])`

**Picture：**

![image](https://user-images.githubusercontent.com/56987319/152400547-7ca16f81-9c43-48a4-9b50-2ec1cef3f4b3.png)

**ERROR LOG：**

ssh://s2110025@vpcc-gpu012:22/home/s2110025/anaconda3/envs/rebel/bin/python3.7 -u /home/s2110025/.pycharm_helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 0.0.0.0 --port 35687 --file /tmp/rebel/src/train.py
Connected to pydev debugger (build 212.5457.59)
pydev debugger: warning: trying to add breakpoint to file that does not exist: /tmp/rebel/src/c:/users/45032/appdata/local/jetbrains/pycharm2021.2/remote_sources/262809266/-1944145685/datasets/load.py (will have no effect)
pydev debugger: warning: trying to add breakpoint to file that does not exist: /tmp/rebel/src/c:/users/45032/appdata/local/jetbrains/pycharm2021.2/remote_sources/262809266/-1944145685/datasets/utils/file_utils.py (will have no effect)
pydev debugger: warning: trying to add breakpoint to file that does not exist: /tmp/rebel/src/c:/users/45032/appdata/local/jetbrains/pycharm2021.2/remote_sources/262809266/-1944145685/datasets/data_files.py (will have no effect)
pydev debugger: warning: trying to add breakpoint to file that does not exist: /tmp/rebel/src/c:/users/45032/appdata/local/jetbrains/pycharm2021.2/remote_sources/262809266/-1944145685/datasets/load.py (will have no effect)
Global seed set to 42
[2022-02-04 02:49:17,204][datasets.builder][WARNING] - Using custom data configuration default-88312dc82d1c9b1a
Downloading and preparing dataset nyt/default to /home/s2110025/.cache/huggingface/datasets/nyt/default-88312dc82d1c9b1a/0.0.0/e31f2476e6cbb27e99672f70a7095c7724f5264e7f64fdf191a41b269249dcde...
0 examples [00:00, ? examples/s][2022-02-04 02:49:17,578][root][INFO] - generating examples from = [PosixPath('/tmp/rebel/datasets/data/nyt/train.json')]
=====================
[PosixPath('/tmp/rebel/datasets/data/nyt/train.json')]
Traceback (most recent call last):
  File "/home/s2110025/anaconda3/envs/rebel/lib/python3.7/site-packages/hydra/_internal/utils.py", line 347, in _run_hydra
    lambda: hydra.run(
  File "/home/s2110025/anaconda3/envs/rebel/lib/python3.7/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/home/s2110025/anaconda3/envs/rebel/lib/python3.7/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/s2110025/anaconda3/envs/rebel/lib/python3.7/site-packages/hydra/_internal/utils.py", line 350, in <lambda>
    overrides=args.overrides,
  File "/home/s2110025/anaconda3/envs/rebel/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 112, in run
    configure_logging=with_log_configuration,
  File "/home/s2110025/anaconda3/envs/rebel/lib/python3.7/site-packages/hydra/core/utils.py", line 127, in run_job
    ret.return_value = task_function(task_cfg)
  File "/tmp/rebel/src/train.py", line 155, in main
    train(conf)
  File "/tmp/rebel/src/train.py", line 100, in train
    pl_data_module = BasePLDataModule(conf, tokenizer, model)
  File "/home/s2110025/anaconda3/envs/rebel/lib/python3.7/site-packages/pytorch_lightning/core/datamodule.py", line 49, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/tmp/rebel/src/pl_data_modules.py", line 68, in __init__
    self.datasets = load_dataset(conf.dataset_name, data_files={'train': conf.train_file, 'dev': conf.validation_file, 'test': conf.test_file})
  File "/home/s2110025/anaconda3/envs/rebel/lib/python3.7/site-packages/datasets/load.py", line 1699, in load_dataset
    use_auth_token=use_auth_token,
  File "/home/s2110025/anaconda3/envs/rebel/lib/python3.7/site-packages/datasets/builder.py", line 596, in download_and_prepare
    dl_manager=dl_manager, verify_infos=verify_infos, **download_and_prepare_kwargs
  File "/home/s2110025/anaconda3/envs/rebel/lib/python3.7/site-packages/datasets/builder.py", line 684, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/home/s2110025/anaconda3/envs/rebel/lib/python3.7/site-packages/datasets/builder.py", line 1081, in _prepare_split
    disable=bool(logging.get_verbosity() == logging.NOTSET),
  File "/home/s2110025/anaconda3/envs/rebel/lib/python3.7/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/s2110025/.cache/huggingface/modules/datasets_modules/datasets/nyt_typed/e31f2476e6cbb27e99672f70a7095c7724f5264e7f64fdf191a41b269249dcde/nyt_typed.py", line 123, in _generate_examples
    list_relations = zip(row['spo_list'],row['spo_details'])
TypeError: list indices must be integers or slices, not str
python-BaseException

Process finished with exit code 1

**Comment by LittlePea13** [comment]
In the [Copy_RE github](https://github.com/xiangrongzeng/copy_re) there seems to be different formats for the files. I believe ours was downloaded from Baidu, because it is the same as the raw dataset file, however words are tokenized and there's a spo_list field instead of relationMentions as in the file they provide in Drive.

I can't seem to be able to download from Baidu at the moment to confirm this, but you have two options, either adapt the nyt.py dataset to read from this other dataset format (should still be very similar) or I can send you the dataset files I have. If you want, reach me to my email, and I will happily provide them.

Best,
Pere-Lluis.

**Comment by DantaAlighieri** [comment]
Ok, Thank you very much. I'll try to use [JointER repo](https://github.com/yubowen-ph/JointER/tree/master/dataset/NYT-multi/data) dataset to run the model.
