### ISSUE TITLE
Error in test.py

### ISSUE THREAD

**Issue by manzoorali29** [Babelscape/rebel#9]
Hi, 
I found below error in the code which shows there is no file or directory FileNotFoundError: [Errno 2] No such file or directory: '/home/manxoor/RelationExtraction/Benchmark_eval/rebel-main/src/outputs/2022-02-17/15-12-18/path_to_checkpoint'

Log:
python test.py model=rebel_model data=nyt_data train=nyt_train do_predict=True checkpoint_path="path_to_checkpoint"
2022-02-17 15:12:16.393884: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/manxoor/opt/openmpi/lib
2022-02-17 15:12:16.393920: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Global seed set to 42
[2022-02-17 15:12:32,330][datasets.builder][WARNING] - Using custom data configuration default-26df38178e3733aa
[2022-02-17 15:12:32,335][datasets.builder][WARNING] - Reusing dataset nyt (/home/manxoor/.cache/huggingface/datasets/nyt/default-26df38178e3733aa/0.0.0/1b5d3bcc4eb4689e4399ba481b0057e167e20cf2a8b0174b677a44c719a131c2)
Traceback (most recent call last):
  File "test.py", line 114, in main
    train(conf)
  File "test.py", line 98, in train
    pl_module = pl_module.load_from_checkpoint(checkpoint_path = conf.checkpoint_path, config = config, tokenizer = tokenizer, model = model)
  File "/home/manxoor/anaconda3/lib/python3.7/site-packages/pytorch_lightning/core/saving.py", line 137, in load_from_checkpoint
    checkpoint = pl_load(checkpoint_path, map_location=lambda storage, loc: storage)
  File "/home/manxoor/anaconda3/lib/python3.7/site-packages/pytorch_lightning/utilities/cloud_io.py", line 31, in load
    with fs.open(path_or_url, "rb") as f:
  File "/home/manxoor/anaconda3/lib/python3.7/site-packages/fsspec/spec.py", line 1036, in open
    **kwargs,
  File "/home/manxoor/anaconda3/lib/python3.7/site-packages/fsspec/implementations/local.py", line 155, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "/home/manxoor/anaconda3/lib/python3.7/site-packages/fsspec/implementations/local.py", line 250, in __init__
    self._open()
  File "/home/manxoor/anaconda3/lib/python3.7/site-packages/fsspec/implementations/local.py", line 255, in _open
    self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/manxoor/RelationExtraction/Benchmark_eval/rebel-main/src/outputs/2022-02-17/15-12-18/path_to_checkpoint'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by ramarasty** [comment]
@manzoorali29 Make sure you have set the right arguments. For example, if you want to test the last checkpoint, set `checkpoint_path` like so:
`python test.py ... checkpoint_path="/home/manxoor/RelationExtraction/Benchmark_eval/rebel-main/src/outputs/2022-02-17/15-12-18/experiments/{{whatever dataset you are working on}}/last.ckpt"`
